version: '3.9'

services:
  docker-mysql:
    image: mysql
    container_name: MercadeoMysql
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
      - ./Scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
    environment:
      - 'MYSQL_ROOT_PASSWORD:mysql'
      - 'MYSQL_DATABASE:mercadeoucab'

  mercadeoucab:
    build: ./backend/
    container_name: mercadeoucabBack
    restart: always
    ports:
      - '8080:8080'
    networks:
      - backend
    depends_on:
      - docker-mysql

volumes:
  db-data:

networks:
  backend:
