version: '3.9'

services:
  mercadeoucab:
    build:
      context: ./backend/
    restart: always
    ports:
      - '8080:8080'
    networks:
      - backend
      - frontend
    depends_on:
      docker-mysql:
        condition: service_healthy

  docker-mysql:
    image: mysql:8.0.23
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - db-data:/var/lib/mysql
      - ./Scripts:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    environment:
      - 'MYSQL_USER=root'
      - 'MYSQL_ROOT_PASSWORD=mysql'
      - 'MYSQL_DATABASE=mercadeoucab'

volumes:
  db-data:

networks:
  backend:
  frontend:
