package mercadeoucab.fabricas.Enums;

public enum Daos {
    DAO,
    DAOCATEGORIA,
    DAODATOENCUESTADO,
    DAOESTADO,
    DAOESTUDIO,
    DAOHIJO,
    DAOMARCA,
    DAOMUESTRAPOBLACION,
    DAOMUNICIPIO,
    DAOOCUPACION,
    DAOOPCION,
    DAOPAIS,
    DAOPARROQUIA,
    DAOPREGUNTA,
    DAOPRESENTACION,
    DAORESPUESTA,
    DAOSOLICITUD,
    DAOSUBCATEGORIA,
    DAOTELEFONO,
    DAOTIPO,
    DAOUSUARIO
}
