package mercadeoucab.fabricas.Enums;

public enum Dtos {
    DTOCATEGORIA,
    DTODATOENCUESTADO,
    DTODIRECTORIOAUSER,
    DTOENCUESTAESTUDIO,
    DTOESTADO,
    DTOESTUDIO,
    DTOHIJO,
    DTO,MAIL,
    DTOMARCA,
    DTOMUESTRAPOBLACION,
    DTOMUNICIPIO,
    DTOOCUPACION,
    DTOOPCION,
    DTOPAIS,
    DTOPARROQUIA,
    DTOPREGUNTA,
    DTOPRESENTACION,
    DTOSOLICITUD,
    DTOSUBCATEGORIA,
    DTOTELEFONO,
    DTOTIPO,
    DTOUSUARIO
}
