package mercadeoucab.fabricas.Enums;

public enum Fabricas {
    CATEGORIA,
    DATOENCUESTADO,
    ENCUESTAESTUDIO,
    ESTADO,
    ESTUDIO,
    HIJO,
    MARCA,
    MUESTRAPOBLACION,
    MUNICIPIO,
    OCUPACION,
    OPCION,
    PAIS,
    PARROQUIA,
    PREGUNTA,
    PRESENTACION,
    RESPUESTA,
    SOLICITUD,
    SUBCATEGORIA,
    TELEFONO,
    TIPO,
    USUARIO,
    MAIL,
    DIRECTORIOACTIVO
}
